### ISSUE TITLE
Minecraft crashes when loading world.

### ISSUE THREAD

**Issue by AlphaCraft9658** [c-leri/Dynamic-Music#9]
I'm playing Minecraft Fabric 1.19.2 with mod version 2.3.0. I have this crash report from Minecraft and also a summary from ChatGPT.

Crash-Report:
```---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-06-19 09:27:19
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at java.base/java.util.KeyValueHolder.<init>(KeyValueHolder.java:62)
	at java.base/java.util.Map.entry(Map.java:1709)
	at net.celeri.dynmus.util.DynamicMusicHelper.getMusicTogglesForType(DynamicMusicHelper.java:305)
	at net.celeri.dynmus.util.DynamicMusicHelper.getToggledCreativeMusicForType(DynamicMusicHelper.java:68)
	at net.minecraft.class_310.handler$zfk000$dynmus$getSituationalMusic(class_310.java:5038)
	at net.minecraft.class_310.method_1544(class_310.java:2523)
	at net.minecraft.class_1142.method_18669(class_1142.java:27)
	at net.minecraft.class_310.method_1574(class_310.java:1859)
	at net.minecraft.class_310.method_1523(class_310.java:1135)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Objects.java:209)
	at java.base/java.util.KeyValueHolder.<init>(KeyValueHolder.java:62)
	at java.base/java.util.Map.entry(Map.java:1709)
	at net.celeri.dynmus.util.DynamicMusicHelper.getMusicTogglesForType(DynamicMusicHelper.java:305)
	at net.celeri.dynmus.util.DynamicMusicHelper.getToggledCreativeMusicForType(DynamicMusicHelper.java:68)
	at net.minecraft.class_310.handler$zfk000$dynmus$getSituationalMusic(class_310.java:5038)
	at net.minecraft.class_310.method_1544(class_310.java:2523)
	at net.minecraft.class_1142.method_18669(class_1142.java:27)

-- Affected level --
Details:
	All players: 1 total; [class_746['AlphaCraft9658'/170, l='ClientLevel', x=-125.11, y=64.00, z=298.99]]
	Chunk stats: 4096, 703
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,76,0), Section: (at 0,12,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 147983 game time, 6000 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:792)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, armorchroma/alternative-icons, minecraft/supporteatinganimation, continuity/default, continuity/glass_pane_culling_fix, VisibleOres2.8.zip, replaymod_lang, Essential (fabric_1.19.2).jar

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 6.2.15-300.fc38.x86_64
	Java Version: 17.0.7, Red Hat, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Red Hat, Inc.
	Memory: 1568162680 bytes (1495 MiB) / 3235905536 bytes (3086 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.50
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: GA104 [GeForce RTX 3070 Ti]
	Graphics card #0 vendor: NVIDIA Corporation (0x10de)
	Graphics card #0 VRAM (MB): 288.00
	Graphics card #0 deviceId: 0x2482
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 32210.95
	Virtual memory used (MB): 8170.89
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 0.00
	JVM Flags: 2 total; -Xms512m -Xmx4096m
	Fabric Mods: 
		alternate-current: Alternate Current 1.6.0
		ambientsounds: Ambient Sounds (Fabric) 5.2.13
		appleskin: AppleSkin 2.4.1+mc1.19
		architectury: Architectury 6.5.85
		armorchroma: Armor Chroma 1.2.3
		betterf3: BetterF3 4.0.0
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		chesttracker: Chest Tracker 1.1.18
			libgui: LibGui 6.3.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
					blue_endless_jankson: jankson 1.2.1
				libninepatch: LibNinePatch 1.1.0
			whereisit: Where Is It 1.14.13
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		clumps: Clumps 9.0.0+14
		continuity: Continuity 2.0.2+1.19
		craftify: Craftify 1.10.0
			vigilance: Vigilance 284
		creativecore: CreativeCore (Fabric) 2.9.3
		dynamicfps: Dynamic FPS 2.2.0
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		dynmus: Dynamic Music 2.3.0+1.19.2
		eatinganimationid: Eating Animation 1.9.1
		ecs: Elytra/Chestplate Swapper 1.2.1-MC1.19
		effective: Effective 1.4
			midnightlib: MidnightLib 0.5.2
		enhancedblockentities: Enhanced Block Entities 0.7.2+1.19.2
		entityculling: EntityCulling-Fabric 1.6.1-mc1.19.2
		essential: Essential 12840+deploy-staging+ge98314a1d
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.0.0
		essential-dependencies: Essential Dependencies 0
			elementa: Elementa 590
			universalcraft: UniversalCraft 270
		extrasounds: ExtraSounds 2.3.1+1.19.2-1.19.1
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
			soundcategories: Sound Categories 1.2.4+1.19
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.25+cafc6e8e90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+1adbf27790
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.8.0+1adbf27790
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.5+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		ferritecore: FerriteCore 5.0.3
		indium: Indium 1.0.9+mc1.19.2
		inventoryprofilesnext: Inventory Profiles Next 1.10.4
		iris: Iris 1.6.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		lambdynlights: LambDynamicLights 2.2.0+1.19.2
			pride: Pride Lib 1.1.2+1.19
			spruceui: SpruceUI 4.1.0+1.19.2
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 3.0.2
		lithium: Lithium 0.11.1
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.2.0-beta.2
		moreculling: More Culling 1.19.1-0.17.0
			conditional-mixin: conditional mixin 0.3.0
		mousetweaks: Mouse Tweaks 2.22
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		notenoughanimations: NotEnoughAnimations 1.6.2
		org_jetbrains_annotations: annotations 13.0
		pickblockpro: Pick Block Pro 1.6.12
		replanter: Replanter 1.3
		replaymod: Replay Mod 1.19.2-2.6.11
		roughlyenoughitems: Roughly Enough Items 9.1.619
			error_notifier: Error Notifier 1.0.9
		signtools: Sign Tools 1.0.3
		skinlayers: 3d Skin Layers 1.5.2-mc1.19.1
		smoothboot: Smooth Boot 1.19-1.7.1
		smoothswapping: Smooth Swapping 0.9.2
		sodium: Sodium 0.4.4+build.18
			org_joml_joml: joml 1.10.4
		sound_physics_remastered: Sound Physics Remastered 1.19.2-1.0.18
		starlight: Starlight 1.1.1+fabric.ae22326
		statuseffecttimer: Status Effect Timer 1.1.1+1.19
		toomanyplayers: Too Many Players 1.19-1.1.4
		voicechat: Simple Voice Chat 1.19.2-2.4.10
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		worldeditcui: WorldEditCUI 1.19.2+01
	Loaded Shaderpack: ComplementaryReimagined_r2.0.3.zip
		Profile: ULTRA (+8 options changed by user)
	NEC status: No NEC detected
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 530.41.03, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, armorchroma/alternative-icons (incompatible), minecraft/supporteatinganimation, continuity/default, continuity/glass_pane_culling_fix, file/VisibleOres2.8.zip
	Current Language: Deutsch (Deutschland)
	CPU: 16x 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['AlphaCraft9658'/170, l='ServerLevel[Fabric Testwelt 1.19]', x=-125.11, y=64.00, z=298.99]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
```

The summary from ChatGPT:
```The provided crash report indicates a null pointer error (NullPointerException) that occurred in the file "DynamicMusicHelper.java". The exact cause of the error lies within the "getMusicTogglesForType" method at line 305 of this file.

In this method, an object of type "KeyValueHolder" is being created, but it contains a null value. The NullPointerException is triggered at the point where an unchecked null check is performed using "Objects.requireNonNull".

It appears that the "getMusicTogglesForType" method is attempting to create a map and is being passed a null value instead of a valid one. This causes the method to fail, resulting in the crash.

It's important to contact the developer of the mod or modpack being used to report this issue. You should inform the developer about the crash report and consider seeking an updated version of the mod or modpack that addresses the error.

Providing additional information to the mod developer, such as the other mods or modifications installed in your game, as well as the exact steps that lead to this crash if you can replicate it, would also be helpful. This will allow the developer to better isolate and resolve the issue.```

**Comment by AlphaCraft9658** [comment]
Okay. Seems like the problem got resolved by deleting the dynmus config directory, which might have had old config formats or files incompatible with the new version and causing severe issues.
